# -*- coding: utf-8 -*-
nombres = [u'Aaron', u'Adam', u'Adrian', u'Adriana', u'Agustin', u'Ainara', u'Ainhoa', u'Aitana', u'Aitor', u'Alba', u'Alberto', 
           u'Alejandra', u'Alejandro', u'Alex', u'Alfonso', u'Alfredo', u'Alicia', u'Alvaro', u'Amparo', u'Ana', u'Ana Belen', 
           u'Ana Isabel', u'Ana Maria', u'Andrea', u'Andres', u'Angel', u'Angela', u'Angeles', u'Anna', u'Antonia', u'Antonio', 
           u'Ariadna', u'Asuncion', u'Aurora', u'Beatriz', u'Belen', u'Benito', u'Blanca', u'Borja', u'Candela', u'Carla', 
           u'Carlos', u'Carlota', u'Carmen', u'Carolina', u'Catalina', u'Celia', u'Clara', u'Claudia', u'Concepcion', u'Consuelo', 
           u'Cristian', u'Cristina', u'Daniel', u'Daniela', u'Dario', u'David', u'Diego', u'Dolores', u'Domingo', u'Eduardo', u'Elena', 
           u'Emilia', u'Emilio', u'Emma', u'Encarnacion', u'Enrique', u'Eric', u'Esperanza', u'Estefania', u'Esther', u'Eugenio', u'Eva', 
           u'Eva Maria', u'Felipe', u'Felisa', u'Felix', u'Fernando', u'Francisca', u'Francisco', u'Francisco Javier', u'Francisco Jose', 
           u'Gabriel', u'Gonzalo', u'Gregorio', u'Guillermo', u'Hector', u'Hugo', u'Ignacio', u'Iker', u'Ines', u'Inmaculada', u'Irene', 
           u'Isabel', u'Ismael', u'Ivan', u'Izan', u'Jaime', u'Javier', u'Jennifer', u'Jessica', u'Jesus', u'Jimena', u'Joan', u'Joaquin', 
           u'Jordi', u'Jorge', u'Jose', u'Jose Antonio', u'Jose Luis', u'Jose Manuel', u'Jose Maria', u'Jose Miguel', u'Jose Ramon', u'Josefa', 
           u'Josefina', u'Josep', u'Juan', u'Juan Antonio', u'Juan Carlos', u'Juan Jose', u'Juan Manuel', u'Juana', u'Julia', u'Julian', 
           u'Julio', u'Laia', u'Laura', u'Leire', u'Leo', u'Leyre', u'Lidia', u'Lola', u'Lorena', u'Lorenzo', u'Lucas', u'Lucia', u'Luis', 
           u'Luisa', u'Manuel', u'Manuela', u'Marc', u'Marcos', u'Margarita', u'Maria', u'Maria Angeles', u'Maria Antonia', u'Maria Asuncion', 
           u'Maria Begoña', u'Maria Belen', u'Maria Carmen', u'Maria Concepcion', u'Maria Dolores', u'Maria Elena', u'Maria Isabel', u'Maria Jesus', 
           u'Maria Jose', u'Maria Josefa', u'Maria Luisa', u'Maria Mar', u'Maria Mercedes', u'Maria Nieves', u'Maria Pilar', u'Maria Rosa', 
           u'Maria Rosario', u'Maria Soledad', u'Maria Teresa', u'Maria Victoria', u'Mariano', u'Marina', u'Mario', u'Marta', u'Martin', u'Martina', 
           u'Mateo', u'Matilde', u'Mercedes', u'Miguel', u'Miguel Angel', u'Milagros', u'Miriam', u'Monica', u'Montserrat', u'Natalia', u'Natividad', 
           u'Nerea', u'Nicolas', u'Noa', u'Noelia', u'Nora', u'Nuria', u'Olga', u'Oscar', u'Pablo', u'Patricia', u'Pau', u'Paula', u'Pedro', u'Petra', 
           u'Pilar', u'Purificacion', u'Rafael', u'Ramon', u'Ramona', u'Raquel', u'Raul', u'Remedios', u'Ricardo', u'Roberto', u'Rocio', u'Rodrigo', 
           u'Rosa', u'Rosa Maria', u'Rosario', u'Ruben', u'Salvador', u'Samuel', u'Sandra', u'Santiago', u'Sara', u'Sebastian', u'Sergio', u'Silvia', 
           u'Sofia', u'Sonia', u'Susana', u'Tamara', u'Tania', u'Teresa', u'Tomas', u'Trinidad', u'Valentina', u'Valeria', u'Vanesa', u'Vanessa', u'Vega', 
           u'Veronica', u'Vicenta', u'Vicente', u'Victor', u'Victoria', u'Yolanda']
